In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
emp = pd.read_csv('employees_data.csv')

In [3]:
emp

    EmployeeID  Age  Gender  Location           JobTitle     Salary
0            1   29    Male    Austin         HR Manager  198686.20
1            2   41    Male    Austin         HR Manager   60732.45
2            3   33  Female   Seattle  Software Engineer  142708.49
3            4   46  Female  New York    Project Manager  178784.12
4            5   25    Male    Austin    Project Manager   88112.93
..         ...  ...     ...       ...                ...        ...
95          96   44    Male    Austin         HR Manager   62135.83
96          97   57    Male   Chicago         HR Manager  170368.31
97          98   27  Female    Austin     Data Scientist   73802.62
98          99   49    Male    Austin    DevOps Engineer   75334.77
99         100   55    Male    Austin     Data Scientist   66374.95

[100 rows x 6 columns]

In [4]:
emp.info()

<class 'pandas.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   EmployeeID  100 non-null    int64
 1   Age         100 non-null    int64
 2   Gender      100 non-null    str
 3   Location    100 non-null    str
 4   JobTitle    100 non-null    str
 5   Salary      100 non-null    float64
dtypes: float64(1), int64(2), str(3)
memory usage: 4.8 KB

In [5]:
emp.duplicated().sum()

np.int64(0)

# Data Profiling

In [33]:
print("\nMissing Values")

print(emp.isnull().sum())

print("\nUnique Values")

print(emp.nunique())

Missing Values
EmployeeID    0
Age           0
Gender        0
Location      0
JobTitle      0
Salary        0
dtype: int64

Unique Values
EmployeeID    100
Age            32
Gender          2
Location        5
JobTitle        5
Salary        100
dtype: int64

In [7]:
print(emp["Gender"].value_counts())

Gender
Male      53
Female    47
Name: count, dtype: int64

In [8]:
print(emp["Salary"].describe())

count       100.000000
mean     128117.620900
std       37795.462034
min       60732.450000
25%       93961.727500
50%      123597.780000
75%      157923.512500
max      198686.200000
Name: Salary, dtype: float64

# Salary Distribution Across Job Titles

In [25]:
salary_job = emp.groupby('JobTitle')['Salary'].agg(AverageSalary='mean',MaximunSalary='max',MinimumSalary='min')
salary_job

            JobTitle  AverageSalary  MaximunSalary  MinimumSalary
0     Data Scientist  123259.875200      185566.89       66374.95
1    DevOps Engineer  121788.738333      193151.71       66161.88
2         HR Manager  130284.838125      198686.20       60732.45
3    Project Manager  143201.954000      198520.58       78401.77
4  Software Engineer  123308.163333      171140.65       88261.39

Insight
- The highest-paid job role is HR Manager and lowest-paid job roles is HR Manager every other job role is average in salary.
- Higher salaries generally correspond to senior or specialized positions.

# Salary Distribution by Gender

In [31]:
gender_salary = emp.groupby('Gender')['Salary'].mean()
gender_salary

Gender
Female    133977.570000
Male      122921.062264
Name: Salary, dtype: float64

Insight
- Compare average salaries of male and female employees we can identify that female earn more as compare to male.
- Detect minor gender pay gap.

# Salary based on location

In [32]:
location_salary = emp.groupby("Location")["Salary"].mean().sort_values(ascending=False)

print(location_salary)

Location
Seattle          135643.638000
San Francisco    129880.460000
Chicago          129783.353913
New York         127754.850870
Austin           117859.209000
Name: Salary, dtype: float64

Insight
- Location-wise Seattle and San Francisco have the highest salaries.
- High-cost cities generally pay more.